# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
import sys
import os
from setuptools_scm import get_version

project = "cloudknot"
copyright = "2024, Adam Richie-Halford, Ariel Rokem"
author = "Adam Richie-Halford"

currentdir = os.path.abspath(os.path.dirname(__file__))


currentdir = os.path.abspath(os.path.dirname(__file__))
sys.path.append(os.path.join(currentdir, "tools"))

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "1.0"  # numpydoc requires sphinx >= 1.0

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# sys.path.append(os.path.abspath("sphinxext"))

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.ifconfig",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    #    "sphinx.ext.githubpages"
    "sphinx_autodoc_typehints",
]

# --- Sphinx Gallery ---

sphinx_gallery_conf = {
    # path to your examples scripts
    "examples_dirs": "../examples",
    # path where to save gallery generated examples
    "gallery_dirs": "auto_examples",
    # To auto-generate example sections in the API
    "doc_module": ("cloudknot",),
    # Auto-generated mini-galleries go here
    "backreferences_dir": "gen_api",
}

# Automatically generate stub pages for API
autoclass_content = "both"  # include both class docstring and __init__
# autodoc_default_flags = ["members", "inherited-members"]

autosummary_generate = True
# numpydoc_show_class_members = False
# Napoleon settings (other than default)
napoleon_google_docstring = False
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_use_param = True

# autodoc-typehints configuration
# typehints_defaults = 'comma'
# simplify_optional_unions = False
# Automatically extract typehints when specified and place them in
# descriptions of the relevant function/method.
# autodoc_typehints = "description"
always_use_bars_union = True

# typehints_use_rtype = False
# typehints_document_rtype = True
typehints_use_signature = True
typehints_use_signature_return = True
# Don't show class signature with the class' name.
autodoc_class_signature = "separated"

if "sphinx_autodoc_defaultargs" in extensions:
    rst_prolog = (
        """
    .. |default| raw:: html

        <div class="default-value-section">"""
        + ' <span class="default-value-label">Default:</span>'
    )

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = get_version(root=currentdir)
# The full version, including alpha/beta/rc tags.
release = get_version(root=currentdir)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "description": "Run your existing python code on AWS Batch",
    "github_user": "nrdg",
    "github_repo": "cloudknot",
    "github_type": "star",
    "show_powered_by": True,
    "fixed_sidebar": True,
}


# If false, no module index is generated.
html_domain_indices = True
# html_domain_indices = False

# Output file base name for HTML help builder.
htmlhelp_basename = "cloudknotdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        "index",
        "cloudknot.tex",
        "cloudknot Documentation",
        "Adam Richie-Halford",
        "manual",
    )
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ("index", "cloudknot", "cloudknot Documentation", ["Adam Richie-Halford"], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        "index",
        "cloudknot",
        "cloudknot Documentation",
        "Adam Richie-Halford",
        "cloudknot",
        "One line description of project.",
        "Miscellaneous",
    )
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = False

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
